/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommoditiesRouteImport } from './routes/commodities'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CommoditySlugRouteImport } from './routes/commodity.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditiesRoute = CommoditiesRouteImport.update({
  id: '/commodities',
  path: '/commodities',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditySlugRoute = CommoditySlugRouteImport.update({
  id: '/commodity/$slug',
  path: '/commodity/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commodities': typeof CommoditiesRoute
  '/countries': typeof CountriesRoute
  '/explore': typeof ExploreRoute
  '/regions': typeof RegionsRoute
  '/search': typeof SearchRoute
  '/commodity/$slug': typeof CommoditySlugRoute
  '/country/$slug': typeof CountrySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commodities': typeof CommoditiesRoute
  '/countries': typeof CountriesRoute
  '/explore': typeof ExploreRoute
  '/regions': typeof RegionsRoute
  '/search': typeof SearchRoute
  '/commodity/$slug': typeof CommoditySlugRoute
  '/country/$slug': typeof CountrySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commodities': typeof CommoditiesRoute
  '/countries': typeof CountriesRoute
  '/explore': typeof ExploreRoute
  '/regions': typeof RegionsRoute
  '/search': typeof SearchRoute
  '/commodity/$slug': typeof CommoditySlugRoute
  '/country/$slug': typeof CountrySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commodities'
    | '/countries'
    | '/explore'
    | '/regions'
    | '/search'
    | '/commodity/$slug'
    | '/country/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commodities'
    | '/countries'
    | '/explore'
    | '/regions'
    | '/search'
    | '/commodity/$slug'
    | '/country/$slug'
  id:
    | '__root__'
    | '/'
    | '/commodities'
    | '/countries'
    | '/explore'
    | '/regions'
    | '/search'
    | '/commodity/$slug'
    | '/country/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommoditiesRoute: typeof CommoditiesRoute
  CountriesRoute: typeof CountriesRoute
  ExploreRoute: typeof ExploreRoute
  RegionsRoute: typeof RegionsRoute
  SearchRoute: typeof SearchRoute
  CommoditySlugRoute: typeof CommoditySlugRoute
  CountrySlugRoute: typeof CountrySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodities': {
      id: '/commodities'
      path: '/commodities'
      fullPath: '/commodities'
      preLoaderRoute: typeof CommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodity/$slug': {
      id: '/commodity/$slug'
      path: '/commodity/$slug'
      fullPath: '/commodity/$slug'
      preLoaderRoute: typeof CommoditySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommoditiesRoute: CommoditiesRoute,
  CountriesRoute: CountriesRoute,
  ExploreRoute: ExploreRoute,
  RegionsRoute: RegionsRoute,
  SearchRoute: SearchRoute,
  CommoditySlugRoute: CommoditySlugRoute,
  CountrySlugRoute: CountrySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
